---
title: "Lab 1 Part 1: Applied Practice, Problem 1 Professional Magic"
author: 'Team03: Savita Chari, Denny Lehman, Tymon Silva'
date: "10/16/2021"
output:
  bookdown::pdf_document2: 
    toc: false
---

# Part 1: Foundational Exercises
## Profesional Magic 

Your aunt (who is a professional magician), claims to have created a pair of magical coins that share a  connection to each other that makes them land in the same way.  The coins are always flipped at the same time.  For a given flip $i \in \{1,2,3...\}$, let $X_i$ be a Bernoulli random variable representing the outcome of the first coin, and let $Y_i$ be a Bernoulli random variable representing the outcome of the second coin.  You assume that each flip of the pair is independent of all other flips of the pair.  You also assume that

$$P(X_i=0)= P(X_i = 1) = P(Y_i=0) = P(Y_i = 1) = 1/2,$$
and write,

$$P(X_i = Y_i) = p.$$

Your aunt claims that $p > 1/2$.

You design a test to evaluate your aunt's claim.  You flip the coins 3 times and define your test statistic to be the sum $X_1 + Y_1 + X_2 + Y_2 + X_3 + Y_3$

Your null hypothesis is that $p=1/2$.  You plan to reject the null if your test statistic is 0 or 6.


1. What is the type 1 error rate of your test?
2. What is the power of your test for the alternate hypothesis that $p=3/4$?

# 1. What is the type 1 error rate of the test?

The type 1 error occurs when we reject the null hypothesis when it is actually true. Type I error, a false positive, is typically denoted as alpha

$$\alpha = P(reject \space Ho|Ho)$$
We are given that Ho is when p = 1/2. p is the probability that Xi = Yi

$$ H_o: p=\frac{1}{2}, \space p=P(X_i = Y_i)$$
Let's define a trial as flipping both coins at the same time, where coin X has outcomes 0 and 1 and coin Y has 0 and 1
$$
X \in \{0,1\} \\
Y \in \{0,1\} \\
\text{Probability of a trial}\\
\theta_i = \text{outcome of two coin flips}\\
Event \space space \space of \space \theta_i\\
\theta_i \in \{\{0,0\},\{0,1\},\{1,0\},\{1,1\}\}\\
P(X=0) = \frac{1}{2} \\
P(Y=0) = \frac{1}{2} \\
P(X=1) = \frac{1}{2} \\
P(Y=1) = \frac{1}{2} \\
P(X=x,Y=y) = P(X=x)*P(Y=y)

$$

If we break down that p statement, we can identify a 

We know that each flip of the pair has the following potential outcomes:
$$
P(X_i=Y_i) = P(X_i=0,Y_i=0) + P(X_i=1,Y_i=1)\\
P(X_i=Y_i|H_o) = 0.5 = P(X_i=0,Y_i=0) + P(X_i=1,Y_i=1)\\
P(X_i=0,Y_i=0)=\frac{1}{4}\\
P(X_i=1,Y_i=1)=\frac{1}{4}
$$
We are also given that our test statistic, theta_hat, will be equal to 

$$
\theta_i = X_i+Y_i\\
\theta_3 =X_1 +Y_1+X_2+Y_2+X_3+Y_3
$$

From the problem definition, we reject the null when our test statistic theta is 0 or 6 after 3 flips of pairs of coins. Type I error is thus
$$
\alpha = P(reject \space Ho|Ho)\\
\alpha = P(\theta_3 \in \{0,6\} |p=\frac{1}{2})\\
\alpha = P(\theta_3=0|p=\frac{1}{2})+P(\theta_3=6|p=\frac{1}{2})
$$
Solve for each term using the binomial distribution formula

$$
binomial \space distribution \space formula \\
P_x = nCx\space q^x(1-q)^{n-x}\\ \\
\text{q was chosen to avoid confusion with p from the problem statement}
$$
$$
solve \space for \space P(\theta_3=0|p=\frac{1}{2})\\
\text{where q is P(X_i=0,Y_i=0)=1/4}\\
\theta_3 = 0\text{ means that after 3 three trials, the test statistic has value of 0 (all 0's) }\\

P(\theta_3=0|p=\frac{1}{2}) = 0C3 \space q^3*(1-q)^0\\
P(\theta_3=0|p=\frac{1}{2}) = (1)(1/4)^3(1)\\
P(\theta_3=0|p=\frac{1}{2})=(1/4)^3
$$
$$
solve \space for \space P(\theta_3=6|p=\frac{1}{2})\\
\text{where q is P(X_i=1,Y_i=1)=1/4}\\
\theta_3 = 6\text{ means after all three trials, the test statistic has the value of 6 (all 1's)}\\

P(\theta_3=6|p=\frac{1}{2}) = 3C3 \space q^3*(1-q)^0\\
P(\theta_3=6|p=\frac{1}{2}) = (1)(1/4)^3(1)\\
P(\theta_3=6|p=\frac{1}{2})=(1/4)^3
$$
now sub back in for alpha
$$
\alpha = P(\theta_3=0|H_o) + P(\theta_3=6|H_o) \\
\alpha = \frac{1}{4}^3 + \frac{1}{4}^3 \\
\alpha = \frac{2}{64} = \frac{1}{32}
$$




# 2. What is the power of your test for the alternate hypothesis that $p=3/4$?

$$Power = 1 - \beta $$
Where $$\beta$$ is the type 2 error, or the false negative rate. Type 2 error occurs when we fail to reject the null hypothesis when we should.

$$
H_a: p=\frac{3}{4}, \space p=P(X_i = Y_i)\\
Power = P(reject \space null|H_a) \\
P(X_i=Y_i) = p = \frac{3}{4}\\
$$
We assume that the likelihood for heads and tails remains the equal, but the likelihood of getting $$X_i = Y_i$$ changes to $$\frac{3}{4}$$. Therefore, 
$$
P(X_i=Y_i|H_a)=3/4 \\
P(X_i=Y_i) = P(X_i=0,Y_i=0)+P(X_i=1,Y_i=1)\\
P(X_i=0,Y_i=0)=P(X_i=1,Y_i=1)\\
\therefore\\
P(X_i=0,Y_i=0) = 3/8 \\
P(X_i=1,Y_i=1) = 3/8 \\
P(X_i=0,Y_i=1) = 1/8\\
P(X_i=1,Y_i=0) = 1/8\\
$$
When fail to reject
$$
\theta_3 = X_1 + Y_1 + X_2 + Y_2+X_3+Y_3\\
\text{reject Ho when } \theta_3 = 0 \space or \space  \theta_3 = 6\\

Power = P(reject \space null|H_a)\\
Power = P(\theta_3 \in \{0,6\}|p=\frac{3}{4})\\
Power=P(\theta_3=0|p=3/4) + P(\theta_3=6|p=3/4)
$$
Now we solve for the two terms
$$
P(\theta_3=0|p=3/4) = 3C0 * (3/8)^3*(1-3/8)^0\\
=(1)(3/8)^3(1)\\
=\frac{27}{512}\\
P(\theta_3=6|p=3/4) = 3C3 * (3/8)^3*(1-3/8)^0\\
=(1)(3/8)^3(1)\\
=\frac{27}{512}\\

$$
$$Power=P(\theta_3=0|p=3/4) + P(\theta_3=6|p=3/4)\\
Power = (\frac{3}{8})^3+(\frac{3}{8})^3\\
Power = 2*(\frac{3}{8})^3\\
Power \approx 0.105
$$

