---
title: "Difficulty Voting in the 2020 Presidential Election"
author: 'Team03: Savita Chari, Denny Lehman, Tymon Silva'
date: "10/16/2021"
output:
  bookdown::pdf_document2: 
    toc: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r load packages, echo=FALSE, warning=FALSE, message=FALSE}
library(plyr)
library(dplyr)
library(ggplot2) 
library(knitr)
library(tidyverse) 
library(haven)
```

# Research Question: Did Democratic voters or Republican voters experience more difficulty voting in the 2020 election?


```{r DATA Read , echo=FALSE, warning=TRUE, message=TRUE}

anes_2020_full_data <- read_csv("anes_timeseries_2020_csv_20210719.csv")

```

```{r DATA WRANGLING , echo=FALSE, warning=TRUE, message=TRUE}
anes_2020_subset <- anes_2020_full_data %>%
  select(Case_Id = V200001
         , Eligibility_Concerns = V200005
         , Eligibility_Outcome = V200006
         , Validation_Study_Outcome = V200008
         , Did_Vote = V202066
         , Political_Party = V201231x
         , Voting_Level_Difficulty_Code = V202119
         )%>%
  filter()

anes_2020_subset
```
```{r}
anes_2020_subset_filtered <- anes_2020_subset%>%
  select(Case_Id
         , Eligibility_Concerns
         , Eligibility_Outcome
         , Validation_Study_Outcome
         , Did_Vote
         , Political_Party
         , Voting_Level_Difficulty_Code
         )%>%
  filter(Voting_Level_Difficulty_Code > 0 
         & Eligibility_Concerns != 3
         & Validation_Study_Outcome != 6
         & Political_Party > 0
         & Political_Party != 4
         )

anes_2020_subset_filtered
```


```{r , echo=FALSE, warning=TRUE, message=TRUE}
anes_2020_subset_final <- anes_2020_subset_filtered %>% 
  mutate(
    Political_Party = case_when(
      Political_Party %in% c(1, 2, 3) ~ 'Democrat', 
       Political_Party %in% c(5, 6, 7) ~ 'Republican',
      ),
    Voting_Level_Difficulty_Code = case_when(
      Voting_Level_Difficulty_Code > 1 ~ 1, 
       Voting_Level_Difficulty_Code == 1 ~ 0,
      )
    )

anes_2020_subset_final
```
```{r}
#anes_2020_subset_final$Political_Party = 'Democrat'
#anes_2020_subset_final
```

```{r Plotting , echo=FALSE, warning=TRUE, message=TRUE, fig.width = 4, fig.height = 4}

anes_2020_difficulty <- anes_2020_subset_final %>%
  select_all()%>%
  filter(Voting_Level_Difficulty_Code == 1)
#anes_2020_difficulty  
df = data.frame(anes_2020_difficulty)

p<-ggplot(data=df, aes(x=Political_Party, y=Voting_Level_Difficulty_Code, fill=Political_Party))+   geom_bar(stat="identity")+
  scale_fill_manual(values=c("#1c2e4a", "#900d09"))+
  theme(legend.position = "none"
        , panel.grid.major = element_blank()
        , panel.grid.minor = element_blank()
        )
p

```

```{r unpaired two sample t-test , echo=FALSE, warning=TRUE, message=TRUE}

t.test(anes_2020_subset_final$Voting_Level_Difficulty_Code ~ anes_2020_subset_final$Political_Party)

```


```{r Wicoxon rank-sum test , echo=FALSE, warning=TRUE, message=TRUE}
anes_2020_subset_final_wilcox <- anes_2020_subset_filtered %>% 
  mutate(
    Political_Party = case_when(
      Political_Party %in% c(1, 2, 3) ~ 'Democrat', 
       Political_Party %in% c(5, 6, 7) ~ 'Republican',
      )
    )

wilcox.test(anes_2020_subset_final_wilcox$Voting_Level_Difficulty_Code ~ anes_2020_subset_final_wilcox$Political_Party)
#H_0 P( difficulty of D < difficulty of R) = P( difficulty of D >= difficulty of R)

```

```{r}


```